### ISSUE TITLE
How to apply for the Claude API more easily?

### ISSUE THREAD

**Issue by zhuyaguang** [jtsang4/claude-to-chatgpt#1]

**Comment by yhyu13** [comment]
same

**Comment by yhyu13** [comment]
Is API key for sale anywhere on the internet?

**Comment by jtsang4** [comment]
Sorry I have no idea about it, I guess I got the API permissions by luck.

**Comment by IAn2018cs** [comment]
> 

是个人申请的吗

**Comment by IAn2018cs** [comment]
> Sorry I have no idea about it, I guess I got the API permissions by luck.
是个人申请的吗

**Comment by jtsang4** [comment]
> > Sorry I have no idea about it, I guess I got the API permissions by luck.
> > 是个人申请的吗

是的，用的也是个人邮箱

**Comment by kakuxuqu** [comment]
where is the Claude API use info  set?
