### ISSUE TITLE
在处理超长对话的时候报错 An error occurred while processing the excessively long conversation.

### ISSUE THREAD

**Issue by JamesFlare1212** [jtsang4/claude-to-chatgpt#11]
CloudFlare Workers 的报错和 https://github.com/jtsang4/claude-to-chatgpt/issues/7 一样，经过一系列排查，我认为是等待 Claude 响应的过程超过了 CloudFlare Workers 的 CPU 时间限制，免费的版本是 10ms。怎么解决还没想法，要么拆成 Chunk，但是似乎不适用。要么升级付费版，有 50ms，但是考虑到有 100k Token Window，我认为也不是好办法。

随后我尝试了 Docker 版本，但是依旧报错，一次是向 Claude 请求超时（太长了），我添加了一个 TimeOut 的参数解决了；第二次超长对话测试，`claude_response` 不存在键 `completion`，导致报错，我就用 `get()` 处理了一下错误。

几次测试下来没问题（33k + 5k Token），提了 PR https://github.com/jtsang4/claude-to-chatgpt/pull/10 作者看看。

---

The error with CloudFlare Workers is the same as https://github.com/jtsang4/claude-to-chatgpt/issues/7. After a series of investigations, I believe that the process of waiting for Claude's response exceeds the CPU time limit of CloudFlare Workers' free version, which is 10ms. I haven't figured out how to solve it yet. Either split it into chunks, but it doesn't seem to be applicable; or upgrade to the paid version, which has 50ms, but considering there are 100k Token Windows, I don't think it's a good solution.

Later on, I tried the Docker version but still encountered errors. The first time was a timeout when requesting from Claude (it took too long), so I added a TimeOut parameter to solve it; and the second time was due to an error where `claude_response` did not have the key `completion`, causing an error. So I used `get()` method to handle this issue.

After several tests (33k + 5k Tokens), everything seems fine and I submitted a PR at https://github.com/jtsang4/claude-to-chatgpt/pull/10 for review by the author.

**Comment by jtsang4** [comment]
感谢👍，已合并
