### ISSUE TITLE
New Model *-0613  and gpt-3.5-turbo-16k

### ISSUE THREAD

**Issue by JamesFlare1212** [jtsang4/claude-to-chatgpt#12]
OpenAI 发布了新模型：

- gpt-4-0613
- gpt-4-32k-0613
- gpt-3.5-turbo-0613
- gpt-3.5-turbo-16k

这些新的参数可能导致原有的程序出现 Bug，或许应更新新的 Mapping 了？

----

OpenAI has released new models:

- gpt-4-0613
- gpt-4-32k-0613
- gpt-3.5-turbo-0613
- gpt-3.5-turbo-16k

These new parameters may cause bugs in existing programs, so perhaps a new mapping should be updated?

**Comment by jtsang4** [comment]
应该还好，默认会 fallback 回 `claude-v1.3-100k`
