### ISSUE TITLE
docker部署无法用chatbox访问

### ISSUE THREAD

**Issue by yujiaxinlong** [jtsang4/claude-to-chatgpt#13]
docker部署的镜像用chatbox访问会一直failed to fetch， 直接curl是可以正常访问的， 用[ChatGPT-Next-Web 也正常。

**Comment by jtsang4** [comment]
看起来和客户端有关，我用 docker 部署在 Chatbox@0.5.2 版本测试没有遇到问题，你用的是 Chatbox 是哪个版本呢

**Comment by JamesFlare1212** [comment]
这个我曾经好像遇到过，我不反代就会failed to fetch，容器也没日志显示，反代后没出现这个问题也就没管。

**Comment by yujiaxinlong** [comment]
> 看起来和客户端有关，我用 docker 部署在 Chatbox@0.5.2 版本测试没有遇到问题，你用的是 Chatbox 是哪个版本呢

也是0.5.2, 后面发现好像是https的原因， 我最后加了域名和证书就可以了。
