### ISSUE TITLE
大佬，咱项目后续还会支持其他claude模型么，比如Claude 1.3 100k

### ISSUE THREAD

**Issue by zisanjun** [jtsang4/claude-to-chatgpt#17]

**Comment by jtsang4** [comment]
Claude 官方文档里已经隐藏了 claude-1.3-100k 的介绍，现在只推荐 `claude-instant-1` 和 `claude-2` 了，如果需要用 `claude-2` 替代就好了

**Comment by zisanjun** [comment]
555555 刚好需要这个模型，那是不是官方隐藏之后就没法改了呀

**Comment by jtsang4** [comment]
> 555555 刚好需要这个模型，那是不是官方隐藏之后就没法改了呀

这个模型版本的参数现在还是可以用的，不过 `claude-1.3-100k` 有 `claude-2` 无法支持的特性吗？

**Comment by zisanjun** [comment]
hh，Claude-1.3-100K和claude2不同的地方就是1.3的限制少一些，在文学描写上的能力会更好，目前是这个情况:D

**Comment by zisanjun** [comment]
大佬，咱这个是不是修改cloudflare-workers.js里面的模型映射表model_map，就可以自行替换模型啦？

**Comment by jtsang4** [comment]
是的，搜索替换这些字符串就好了

**Comment by zisanjun** [comment]
感恩！谢谢大佬指点！

**Comment by zisanjun** [comment]
大佬，我是用docker部署的，为什么修改完cloudflare-workers.js，重启docker之后依旧没有生效？

**Comment by zisanjun** [comment]
models.py是不是也要修改？还有没有其他文件呀

**Comment by jtsang4** [comment]
> models.py是不是也要修改？还有没有其他文件呀

你是用 Docker 部署的啊，那不需要修改 `cloudflare-workers.js`，这个只是用 Cloudflare Worker 部署才要改的。如果是 Docker 版本可以全局搜索 py 文件里的内容做修改

**Comment by zisanjun** [comment]
昨天忘记反馈啦，反馈：models.py修改完成之后就可以啦！感谢大佬指点！

**Comment by jtsang4** [comment]
👍 赞，这个 issue 我先关闭了
