### ISSUE TITLE
Add Support to Claude 3

### ISSUE THREAD

**Issue by vcarus** [jtsang4/claude-to-chatgpt#29]
Please add support to claude 3.

Model comparison:
https://docs.anthropic.com/claude/docs/models-overview#model-comparison

API changes:  Text Completions -> Messages
https://docs.anthropic.com/claude/reference/migrating-from-text-completions-to-messages

**Comment by jtsang4** [comment]
I don't have a available Claude API key currently. The previous key has been recycled. If you have a available key, PR is also welcome.

**Comment by jtsang4** [comment]
> Check your mailbox, key should be there😉

Great, received the key. I will try to support the latest model in my spare time.

**Comment by qebas** [comment]
Hi @jtsang4 , are you still planning to update support for Claude 3 or is this an abandoned project?

**Comment by jtsang4** [comment]
> Hi @jtsang4, are you still planning to update support for Claude 3 or is this an abandoned project?

I'm not sure if it's necessary, projects like https://github.com/songquanpeng/one-api have already done a great job. Will it become a better choice?  If there are still people in need, I can provide some support.

**Comment by qebas** [comment]
> > Hi @jtsang4, are you still planning to update support for Claude 3 or is this an abandoned project?
> 
> I'm not sure if it's necessary, projects like https://github.com/songquanpeng/one-api have already done a great job. Will it become a better choice? If there are still people in need, I can provide some support.

The project you mentioned doesn't provide a Cloudflare Worker solution, which is quite useful, just wondering if it's not much work, you could upgrade this project.

Thank you

**Comment by jtsang4** [comment]
The cloudflare worker's version has been updated, new API and model are supported now, and the model name could be Claude's model like`claude-3-haiku-20240307` directly.
