### ISSUE TITLE
聊着聊天总是断掉，Cloudflare 日志显示 The script will never generate a response

### ISSUE THREAD

**Issue by liuzhiguo630** [jtsang4/claude-to-chatgpt#7]

**Comment by jtsang4** [comment]
可以到 Cloudflare Workers 的日志里看下请求和返回的情况，这个日志的表现说明请求走到了无返回的分支上。可以检查下是不是 API Key 填错了，需要按照 OpenAPI Chat API 的方式填写

**Comment by JamesFlare1212** [comment]
这个就是CPU时间不够了，建议用Docker。

**Comment by liuzhiguo630** [comment]
> 这个就是CPU时间不够了，建议用Docker。

不是，这个问题我已经解决了。

**Comment by cwyalpha** [comment]
> > 这个就是CPU时间不够了，建议用Docker。
> 
> 不是，这个问题我已经解决了。

同这个报错，请问是如何解决的？
